### ISSUE TITLE
Direct load with hexademical written as decimal results in NPE

### ISSUE THREAD

**Issue by SealOfTime** [tune-it/bcomp#10]
Sadly, BCOMP-NG does not properly handle STDOUT redirection, so here is manual Copy-paste from system console [log.txt](https://github.com/tune-it/bcomp/files/4638062/log.txt) of event caused by
following code:
```
ORG 0x1C
START: LOOP START
       LD   #FF
```
Similar issue occurs with following code:
```
ORG FF
START: LOOP START
```
But with a different error message: [log2.txt](https://github.com/tune-it/bcomp/files/4638065/log2.txt)

In all of these events nothing is #printed in BCOMP log window.
![image](https://user-images.githubusercontent.com/53912341/82115356-f7ec2f80-976a-11ea-9005-6cd49484c66d.png)

Weirdly, when only `ORG FF` is present in the program without any functional code assembler compilation error is correctly printed into BCOMP log window and no JVM errors are noticed
![image](https://user-images.githubusercontent.com/53912341/82115330-d68b4380-976a-11ea-8aa3-61b0de4d14d6.png)

**Comment by serge-klimenkov** [comment]
Confirmed, fix proposed
