### ISSUE TITLE
Добавьте ВУ-10 "Пульт от ядерки"

### ISSUE THREAD

**Issue by worthant** [tune-it/bcomp#26]
Чтобы можно было в любой момент по указанию практика прервать выполнение "полезной программы" и обработать должным образом

**Comment by Zerumi** [comment]
Very useful stuff!

**Comment by Ne0Ment** [comment]
bcomp is literally unusable without this feature.

**Comment by nightness333** [comment]
I think this feature will take the product to a new level! You have to add it!

**Comment by Kuchizu** [comment]
[Yes.](https://mf.b37mrtl.ru/russian/images/2020.09/article/5f58f17b02e8bd1f7e4331b5.jpg)

**Comment by Catwithraincoat** [comment]
Obviously it's necessary

**Comment by MATPOCKuH** [comment]
Не вижу сути issue
