### ISSUE TITLE
ВУ-0 (Таймер) генерирует одно прерывание многократно

### ISSUE THREAD

**Issue by r3tnu** [tune-it/bcomp#29]
После гененрирования первого прерывания ВУ-0 продолжает генерировает его многократно, по выходу из первого прерывания.

Способ репликации:
```
        ORG     0x0
V0:     WORD    $INT0, 0x180

        ORG     0x40
START:  DI
        CLA
        LD      #0x8    ;ENABLES INTERRUPT ON TIMER
        OUT     0x1
        LD      #0xA    ;SETS THE INTERRUPT TIME TO 1 SECOND
        OUT     0x0
        CLA
        EI

LP:     ADD #0x1
        JUMP LP

INT0:   
        NOP
        IRET
```

Однако, если перед выходом из прерывания записывать в DR значение, то прерывание больше не генерируется:

```
; То же что и в прошлом примере

INT0:   
        NOP
        LD     #0xA
        OUT      0x0
        IRET
```

**Comment by MATPOCKuH** [comment]
Учим теорию. Так и должно быть.
Факт генерации прерывания не гарантирует обработку запроса от именно этого КВУ в обработчике.
Готовность не сброшена => продолжаем запрашивать готовность далее.
Для сброса готовности можно, например, использовать фиктивное чтение из РД КВУ0

**Comment by MATPOCKuH** [comment]
Учим теорию. Так и должно быть.
Факт генерации прерывания не гарантирует обработку запроса от именно этого КВУ в обработчике.
Готовность не сброшена => продолжаем запрашивать готовность далее.
Для сброса готовности можно, например, использовать фиктивное чтение из РД КВУ0
